export default [
  "web",
  "react",
  "flutter",
  "app",
  "ad",
  "ads",
  "seo",
  "graphic",
  "poster",
  "freelance",
  "design",
  "designer",
  "webmasater",
  "web master",
  "website",
  "site",
  "flyer",
  "adobe",
  // general design & creative
  "graphic design",
  "web design",
  "ui design",
  "ux design",
  "logo design",
  "branding",
  "illustration",
  "digital design",
  "visual design",
  "motion graphics",
  "poster design",
  "print design",
  "flyer design",
  "social media graphics",
  "packaging design",
  "banner design",
  "infographic design",

  // tools & platforms (design)
  "photoshop",
  "illustrator",
  "indesign",
  "figma",
  "canva",
  "adobe xd",
  "sketch",
  "coreldraw",
  "affinity designer",

  // web platforms
  "wordpress",
  "wix",
  "webflow",
  "shopify",
  "squarespace",
  "elementor",
  "woocommerce",
  "joomla",
  "drupal",
  "cms design",

  // frontend development
  "html",
  "css",
  "javascript",
  "typescript",
  "react",
  "vue",
  "tailwind css",
  "bootstrap",
  "sass",
  "next.js",
  "frontend developer",

  // backend & fullstack
  "node.js",
  "express.js",
  "mongodb",
  "postgresql",
  "mysql",
  "firebase",
  "django",
  "laravel",
  "api integration",
  "full stack developer",
  "backend developer",

  // dev tools / extra
  "git",
  "github",
  "rest api",
  "cpanel",
  "seo optimization",
  "web performance",
  "domain setup",
  "web hosting",
  "responsive design",
  "mobile optimization",
];
